server:
  port: 8082

#mysql数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.230/sboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update

  #redis 配置
  redis:
    host: 192.168.100.230
    password: 123456
    database: 0
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 8
        #最大等待时间(负值表示没有限制)
        max-wait: -1
        #最大空闲连接
        max-idle: 8
        #最小空闲连接
        min-idle: 0
    #连接超时时间(毫秒)
    timeout: 3000

logging:
  level:
    org.chp: warn