server:
  port: 8082

#mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.230/sboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  #spring data jpa配置
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true