
#redis配置
spring:
  redis:
    host: 192.168.100.230
    password: 123456
    database: 0
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 8
        #最大等待时间(负值表示没有限制)
        max-wait: -1
        #最大空闲连接
        max-idle: 8
        #最小空闲连接
        min-idle: 0
    #连接超时时间(毫秒)
    timeout: 3000
